config/routes.rb
Rails.application.routes.draw do
	
	resources :pets
  resources :customers
 
	get '/add_pets', to: 'pets#add_pets'
	get '/randomize_pets', to: 'pets#randomize'
	get '/truncate_pets', to: 'pets#truncate_pets'
	
	get '/add_customers', to: 'customers#add_customers'
	get '/truncate_customers', to: 'customers#truncate_customers'
	
	root 'customers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :pets
 
	def self.add_customers
		customer_list = [
			['Kirstin', 'kmacbrearty0@fotki.com', 'Jelisavac'],
			['Tobi', 'tdowyer1@lulu.com', 'Castlepollard'],
			['Bobbee', 'bmcrill2@surveymonkey.com', 'Māymay'],
			['Kara', 'kurion3@nyu.edu', 'Kinnula'],
			['Robinet', 'rrippin4@youtube.com', 'Yulin'],
			['Ros', 'rroberson5@arizona.edu', 'Belene'],
			['Shelley', 'sscimonelli6@istockphoto.com', 'Jabon'],
			['Salim', 'sdalessio7@storify.com', 'Luxor'],
			['Connie', 'cmyhan8@gravatar.com', 'Tonoshō'],
			['Lorrie', 'lheningham9@nbcnews.com', 'Ishioka'],
			['Dolley', 'daddersona@com.com', 'Pentéli'],
			['Cherish', 'cgregoryb@purevolume.com', 'Jinshan'],
			['Jayme', 'jbickersc@berkeley.edu', 'Concepcion'],
			['Cammi', 'cbaserd@parallels.com', 'Independencia'],
			['Lock', 'laudreye@pbs.org', 'Independencia'],
			['Karisa', 'kwoodf@europa.eu', 'Zgłobień'],
			['Brand', 'bdumbrillg@redcross.org', 'Longsheng'],
			['Rip', 'rmcavaddyh@dion.ne.jp', 'Saguday'],
			['Mal', 'mswiffini@dell.com', 'Sabanalarga'],
			['Viola', 'vmcdonoghj@diigo.com', 'Granadero Baigorria'],
			['Shir', 'smardyk@theglobeandmail.com', 'Alegria'],
			['My', 'mkneebonel@google.it', 'Luofang'],
			['Gwenni', 'gsollimem@princeton.edu', 'Марино'],
			['Isidor', 'ishawn@mashable.com', 'Aasiaat'],
			['Tudor', 'tlaurenzo@sciencedirect.com', 'Bauan'],
			['Nathalia', 'norrillp@chicagotribune.com', 'San Pedro Ayampuc'],
			['Ava', 'aduxbarryq@sohu.com', 'Patpata Segundo'],
			['Baily', 'bdavidover@etsy.com', 'Meruge'],
			['Odella', 'obenadettes@cdbaby.com', 'Zhulan'],
			['Neala', 'nrizzillot@reverbnation.com', 'Āqchah'],
			['Nataline', 'ndyshartu@hugedomains.com', 'Saint-Brieuc'],
			['Nowell', 'nrobinettv@cdbaby.com', 'Eshan'],
			['Abdel', 'awenzelw@latimes.com', 'Ciego de Ávila'],
			['Hermy', 'hrickmanx@phpbb.com', 'Smolenskaya'],
			['Ileana', 'igopsilly@webs.com', 'Radoboj'],
			['Giraldo', 'gbanaszewskiz@google.co.jp', 'Ishikawa'],
			['Noby', 'nwaind10@desdev.cn', 'Fatualam'],
			['Dominik', 'daireton11@ehow.com', 'San José del Guaviare'],
			['Borden', 'bheinssen12@topsy.com', 'Lens'],
			['Nancey', 'nbaroux13@rakuten.co.jp', 'Santa Bárbara']
		]
	
		customer_list.each do |item|
			sql = "insert into customers (name, email, city) values ('#{item[0]}', '#{item[1]}', '#{item[2]}')"
 			ActiveRecord::Base.connection.exec_query(sql)
		end
	end

	def self.truncate_customers
		ActiveRecord::Base.connection.exec_query("TRUNCATE TABLE customers;")
	end
end

app/models/pet.rb
class Pet < ApplicationRecord
	belongs_to :customer

  def self.add_pets
			pet_list = [
			'Brolga crane', 
			'Bear, sloth', 
			'Ovenbird', 
			'Pademelon, red-legged', 
			'Nilgai', 
			'Black-fronted bulbul', 
			'White-necked raven', 
			'Dabchick', 
			'Marten, american', 
			'Sun gazer', 
			'Bat, asian false vampire', 
			'Gonolek, burchell''s', 
			'Woodpecker, downy', 
			'Squirrel, golden-mantled ground', 
			'River wallaby', 
			'Lourie, grey', 
			'South American sea lion', 
			'Squirrel, eurasian red', 
			'Owl, white-browed', 
			'Finch, common melba', 
			'Suricate', 
			'Pine squirrel', 
			'Brush-tailed phascogale', 
			'Gull, pacific', 
			'Seal, harbor', 
			'Lapwing (unidentified)', 
			'Ringtail', 
			'Otter, brazilian', 
			'Flamingo, chilean', 
			'Eastern indigo snake', 
			'Rabbit, eastern cottontail', 
			'Fowl, helmeted guinea', 
			'Marine iguana', 
			'Vulture, black', 
			'Raven, cape', 
			'Sandpiper, spotted wood', 
			'Sally lightfoot crab', 
			'Dove, laughing', 
			'Bear', 
			'Possum, common brushtail', 
		]
		pet_list.each do |pet_name|
			sql = "insert into pets (name) values ('#{pet_name}')"
 			ActiveRecord::Base.connection.exec_query(sql)
		end
	end

	def self.truncate_pets
		ActiveRecord::Base.connection.exec_query("TRUNCATE TABLE pets;")
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def index
		@customers = Customer.all
	end

	def add_customers
		Customer.add_customers
		@customers = Customer.all
		redirect_to customers_path
	end

	def truncate_customers
		Customer.truncate_customers
		@customers = Customer.all
		render 'customers/index'
	end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

	def randomize
		Pet.all.each do |p| 
			custid = (2..Customer.all.count).to_a.sample
			p.customer_id = custid
			p.save
		end
		@customers = Customer.all
		render 'customers/index'
	end
 
	def add_pets
		Pet.add_pets
		@customers = Customer.all
		render 'customers/index'
	end
 
	def truncate_pets
		Pet.truncate_pets
		@customers = Customer.all
		render 'customers/index'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/customers/index.html.erb
<div class="container">
	<div class="row">
		<h1>Customers and Pets</h1>
	</div>
	
	<div class="row">
		<div class="col-lg-2">
			<nav class="nav flex-column">
				<%= link_to 'Add Customers', add_customers_path %>
				<%= link_to 'Remove Customers', truncate_customers_path %>
				<%= link_to 'Add Pets', add_pets_path %>
				<%= link_to 'Rearrange Pets', randomize_pets_path %>
				<%= link_to 'Remove Pets', truncate_pets_path %>
			</nav>
		</div>

		<div class="col-lg-9">
			<div class="row">

			<% @customers.each do |customer| %>
				<div class="col-lg-4	customer">
					<h3><%= customer.name %></h3>
					<p>email: <%= customer.email %></p>
					<p>city: <%= customer.city %></p>
					<% if customer.pets %>
						<p>pet(s):</p>
						<ul>
							<% customer.pets.each do |pet| %>
								<li><%= pet.name %></li>
							<% end %>
						</ul>
					<% end %>
				</div>
			<% end %>
			
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->		
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>MySQL!</title>
  </head>
  <body>
    
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pets/index.html.erb
<h1>Pets</h1>

<% @pets.each do |pet| %>
	<p><%= pet.name %></p>
<hr />
	<% end %>